//! fabric-language-rust trampoline.
//!
//! This is the only native library with Java-visible symbols. It backs the
//! `native` methods on `io.github.bownlux.fabricrust.NativeBridge` and forwards
//! into consumer cdylibs, which are opened with `libloading` (dlopen) and expose
//! a single well-known symbol, `fabric_rust_register` (Boundary 2).
//!
//! Nothing here may unwind into the JVM. Every export runs its body inside
//! [`EnvUnowned::with_env`] (which wraps the closure in `catch_unwind`), and
//! errors or panics are resolved with [`ThrowRuntimeExAndDefault`]: throw a
//! `java.lang.RuntimeException`, return a default value.

use std::ffi::c_void;

use jni::EnvUnowned;
use jni::errors::ThrowRuntimeExAndDefault;
use jni::objects::JString;
use jni::sys;

/// Signature of the well-known registration symbol every fabric-rust consumer
/// cdylib exports (FFI Boundary 2).
type RegisterFn = unsafe extern "system" fn(*mut sys::JNIEnv, sys::jobject) -> sys::jint;

/// Signature of every registered entrypoint function (shims generated by the
/// `fabric_rust::register_entrypoints!` macro).
type EntrypointFn = unsafe extern "system" fn(*mut sys::JNIEnv);

/// Error type carrying either a JNI error or a plain message. Thrown to Java as
/// a `RuntimeException` by the [`ThrowRuntimeExAndDefault`] policy.
#[derive(Debug)]
enum BridgeError {
    Jni(jni::errors::Error),
    Msg(String),
}

impl std::fmt::Display for BridgeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BridgeError::Jni(e) => write!(f, "{e}"),
            BridgeError::Msg(m) => f.write_str(m),
        }
    }
}

impl std::error::Error for BridgeError {}

impl From<jni::errors::Error> for BridgeError {
    fn from(e: jni::errors::Error) -> Self {
        BridgeError::Jni(e)
    }
}

/// Called by the JVM when `NativeBridge.initialize` does `System.load` on this
/// library. Registers this crate's process-wide [`jni::JavaVM`] singleton and
/// reports the JNI version we require.
///
/// Must not unwind: the body is wrapped in `catch_unwind`.
#[unsafe(no_mangle)]
pub extern "system" fn JNI_OnLoad(vm: *mut sys::JavaVM, _reserved: *mut c_void) -> sys::jint {
    std::panic::catch_unwind(|| {
        if vm.is_null() {
            return sys::JNI_ERR;
        }
        // Registers the process-wide JavaVM singleton for this copy of the
        // `jni` crate statics (each cdylib carries its own copy).
        let _vm = unsafe { jni::JavaVM::from_raw(vm) };
        sys::JNI_VERSION_1_8
    })
    .unwrap_or(sys::JNI_ERR)
}

/// `static native long openLibrary(String absolutePath)`
///
/// Opens a consumer cdylib with `libloading` (dlopen). The [`libloading::Library`]
/// is leaked on purpose (`Box::into_raw`): function pointers handed to Java must
/// never dangle. Returns the leaked pointer as a `jlong` handle. On failure,
/// throws `java.lang.RuntimeException` (carrying the OS error) and returns 0.
#[unsafe(no_mangle)]
pub extern "system" fn Java_io_github_bownlux_fabricrust_NativeBridge_openLibrary(
    env: *mut sys::JNIEnv,
    _class: sys::jclass,
    path: sys::jstring,
) -> sys::jlong {
    // Safety: the JVM passes a valid, attached JNIEnv pointer to native methods.
    let mut unowned = unsafe { EnvUnowned::from_raw(env) };
    unowned
        .with_env(|env| -> Result<sys::jlong, BridgeError> {
            // Safety: `path` is the jstring argument of this native method call
            // and belongs to the current JNI stack frame.
            let path = unsafe { JString::from_raw(env, path) };
            let path: String = path
                .try_to_string(env)
                .map_err(|e| BridgeError::Msg(format!("openLibrary: invalid path argument: {e}")))?;

            // Safety: loading an arbitrary library can run arbitrary
            // constructors; that's what this method exists to do. The Java
            // side vetted the path (it extracted the file from a mod jar).
            let library = unsafe { libloading::Library::new(&path) }.map_err(|e| {
                BridgeError::Msg(format!("failed to load native library `{path}`: {e}"))
            })?;

            // Leak on purpose: registered fn pointers must stay valid forever.
            let handle = Box::into_raw(Box::new(library));
            Ok(handle as usize as sys::jlong)
        })
        .resolve::<ThrowRuntimeExAndDefault>()
}

/// `static native int registerMod(long handle, EntrypointRegistrar registrar)`
///
/// Looks up the well-known `fabric_rust_register` symbol in the library behind
/// `handle` and calls it with the registrar object. Returns whatever ABI
/// version the library reported. Throws `RuntimeException` if the handle is
/// invalid or the symbol is missing.
#[unsafe(no_mangle)]
pub extern "system" fn Java_io_github_bownlux_fabricrust_NativeBridge_registerMod(
    env: *mut sys::JNIEnv,
    _class: sys::jclass,
    handle: sys::jlong,
    registrar: sys::jobject,
) -> sys::jint {
    // Safety: the JVM passes a valid, attached JNIEnv pointer to native methods.
    let mut unowned = unsafe { EnvUnowned::from_raw(env) };
    unowned
        .with_env(|env| -> Result<sys::jint, BridgeError> {
            if handle == 0 {
                return Err(BridgeError::Msg(
                    "registerMod called with an invalid library handle (0)".to_string(),
                ));
            }
            if registrar.is_null() {
                return Err(BridgeError::Msg(
                    "registerMod called with a null registrar".to_string(),
                ));
            }
            // Safety: `handle` is a pointer produced by `openLibrary` above and
            // the library is leaked, so it is still alive.
            let library = unsafe { &*(handle as usize as *const libloading::Library) };

            // Safety: symbol type is the fixed Boundary-2 contract signature.
            let register: RegisterFn =
                match unsafe { library.get::<RegisterFn>(b"fabric_rust_register\0") } {
                    Ok(symbol) => *symbol,
                    Err(_) => {
                        return Err(BridgeError::Msg(
                            "the loaded library is not a fabric-rust library \
                             (missing fabric_rust_register)"
                                .to_string(),
                        ));
                    }
                };

            let raw_env = env.get_raw();
            // Safety: `register` matches the Boundary-2 ABI; we pass the raw
            // env of the current native frame and the registrar local ref that
            // belongs to that same frame. The callee catches its own panics.
            let abi = unsafe { register(raw_env, registrar) };
            Ok(abi)
        })
        .resolve::<ThrowRuntimeExAndDefault>()
}

/// `static native void invokeEntrypoint(long fnPtr)`
///
/// Calls a previously-registered entrypoint function pointer with the current
/// raw env. Rejects 0 with a thrown `RuntimeException`.
///
/// fn-ptr <-> usize <-> jlong round-trips are well-defined; provenance rules
/// only constrain data pointers.
#[unsafe(no_mangle)]
pub extern "system" fn Java_io_github_bownlux_fabricrust_NativeBridge_invokeEntrypoint(
    env: *mut sys::JNIEnv,
    _class: sys::jclass,
    fn_ptr: sys::jlong,
) {
    // Safety: the JVM passes a valid, attached JNIEnv pointer to native methods.
    let mut unowned = unsafe { EnvUnowned::from_raw(env) };
    unowned
        .with_env(|env| -> Result<(), BridgeError> {
            if fn_ptr == 0 {
                return Err(BridgeError::Msg(
                    "invokeEntrypoint called with a null entrypoint pointer (0)".to_string(),
                ));
            }
            // Safety: the only source of non-zero fnPtr values is the
            // registrar upcall performed by `fabric_rust_register`, which
            // registers shims of exactly this signature; libraries are leaked
            // so the pointer cannot dangle.
            let entrypoint: EntrypointFn =
                unsafe { std::mem::transmute::<usize, EntrypointFn>(fn_ptr as usize) };
            let raw_env = env.get_raw();
            // Safety: entrypoint shims catch their own panics (SDK-generated).
            unsafe { entrypoint(raw_env) };
            Ok(())
        })
        .resolve::<ThrowRuntimeExAndDefault>()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bridge_error_display_passes_message_through() {
        let err = BridgeError::Msg("the loaded library is not a fabric-rust library \
                                    (missing fabric_rust_register)"
            .to_string());
        assert!(err.to_string().contains("missing fabric_rust_register"));
    }

    #[test]
    fn bridge_error_wraps_jni_errors() {
        let err = BridgeError::from(jni::errors::Error::UninitializedJavaVM);
        assert!(matches!(err, BridgeError::Jni(_)));
        assert!(!err.to_string().is_empty());
    }

    #[test]
    fn fn_ptr_jlong_round_trip_is_lossless() {
        unsafe extern "system" fn probe(_env: *mut sys::JNIEnv) {}
        let original = probe as EntrypointFn;
        let as_jlong = original as usize as sys::jlong;
        assert_ne!(as_jlong, 0);
        let back: EntrypointFn = unsafe { std::mem::transmute::<usize, EntrypointFn>(as_jlong as usize) };
        assert_eq!(back as usize, original as usize);
    }
}
