//! Proc macros for the fabric-rust SDK.
//!
//! The only export is [`register_entrypoints!`], normally consumed through its
//! re-export as `fabric_rust::register_entrypoints!`.

use proc_macro2::{Span, TokenStream};
use quote::{format_ident, quote};
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{LitStr, Path, Token};

/// Declares the Rust entrypoints of a fabric-rust mod cdylib.
///
/// ```ignore
/// fn init() { /* ... */ }
///
/// fabric_rust::register_entrypoints! {
///     "init" => init,
/// }
/// ```
///
/// Expands to the single well-known `fabric_rust_register` export (FFI
/// Boundary 2), which hands the entry table to
/// `fabric_rust::__internal::register`, plus one
/// `unsafe extern "system" fn(*mut jni::sys::JNIEnv)` shim per entry. Each
/// shim calls your plain `fn()` and catches panics, throwing them as Java
/// `RuntimeException`s instead of unwinding into the JVM.
///
/// Compile-fails on duplicate entrypoint names or an empty list.
#[proc_macro]
pub fn register_entrypoints(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    expand(input.into()).into()
}

struct Entry {
    name: LitStr,
    target: Path,
}

impl Parse for Entry {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let name: LitStr = input.parse()?;
        input.parse::<Token![=>]>()?;
        let target: Path = input.parse()?;
        Ok(Entry { name, target })
    }
}

struct Entries {
    entries: Punctuated<Entry, Token![,]>,
}

impl Parse for Entries {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        Ok(Entries {
            entries: Punctuated::parse_terminated(input)?,
        })
    }
}

fn expand(input: TokenStream) -> TokenStream {
    let parsed: Entries = match syn::parse2(input) {
        Ok(parsed) => parsed,
        Err(err) => return err.to_compile_error(),
    };
    let entries: Vec<Entry> = parsed.entries.into_iter().collect();

    if entries.is_empty() {
        return syn::Error::new(
            Span::call_site(),
            "register_entrypoints! requires at least one `\"name\" => fn_path` entry",
        )
        .to_compile_error();
    }

    let mut seen: Vec<String> = Vec::new();
    for entry in &entries {
        let name = entry.name.value();
        if name.is_empty() {
            return syn::Error::new(
                entry.name.span(),
                "entrypoint name must not be empty",
            )
            .to_compile_error();
        }
        if seen.contains(&name) {
            return syn::Error::new(
                entry.name.span(),
                format!("duplicate entrypoint name `{name}`"),
            )
            .to_compile_error();
        }
        seen.push(name);
    }

    let table_entries = entries.iter().enumerate().map(|(index, entry)| {
        let shim = format_ident!("__fabric_rust_shim_{index}");
        let name = &entry.name;
        let target = &entry.target;
        quote! {
            {
                /// Panic-catching shim generated by `register_entrypoints!`.
                unsafe extern "system" fn #shim(
                    env: *mut ::fabric_rust::jni::sys::JNIEnv,
                ) {
                    // Coercion site: the author's entrypoint must be a plain
                    // zero-argument function.
                    let entrypoint: fn() = #target;
                    // Safety: the trampoline passes the current native
                    // frame's valid, attached JNIEnv pointer.
                    unsafe {
                        ::fabric_rust::__internal::invoke_entrypoint(env, entrypoint, #name);
                    }
                }
                (#name, #shim as ::fabric_rust::__internal::EntrypointFn)
            }
        }
    });

    quote! {
        /// Well-known fabric-rust registration export (FFI Boundary 2),
        /// generated by `fabric_rust::register_entrypoints!`.
        #[unsafe(no_mangle)]
        pub extern "system" fn fabric_rust_register(
            env: *mut ::fabric_rust::jni::sys::JNIEnv,
            registrar: ::fabric_rust::jni::sys::jobject,
        ) -> ::fabric_rust::jni::sys::jint {
            let __fabric_rust_entries: &[(&str, ::fabric_rust::__internal::EntrypointFn)] = &[
                #(#table_entries),*
            ];
            // Safety: the JVM invoked us through the trampoline's registerMod
            // native method, so `env` is the valid, attached JNIEnv of this
            // frame and `registrar` a valid local reference within it.
            unsafe {
                ::fabric_rust::__internal::register(env, registrar, __fabric_rust_entries)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;

    fn expand_str(input: TokenStream) -> String {
        expand(input).to_string()
    }

    #[test]
    fn generates_register_export_and_shims() {
        let out = expand_str(quote! { "init" => init, "other" => path::to::other });
        assert!(out.contains("fabric_rust_register"));
        assert!(out.contains("__fabric_rust_shim_0"));
        assert!(out.contains("__fabric_rust_shim_1"));
        assert!(out.contains(":: fabric_rust :: __internal :: register"));
        assert!(out.contains(":: fabric_rust :: __internal :: invoke_entrypoint"));
        assert!(!out.contains("compile_error"));
    }

    #[test]
    fn accepts_trailing_comma_and_no_trailing_comma() {
        assert!(!expand_str(quote! { "init" => init }).contains("compile_error"));
        assert!(!expand_str(quote! { "init" => init, }).contains("compile_error"));
    }

    #[test]
    fn rejects_empty_list() {
        let out = expand_str(quote! {});
        assert!(out.contains("compile_error"));
        assert!(out.contains("at least one"));
    }

    #[test]
    fn rejects_duplicate_names() {
        let out = expand_str(quote! { "init" => a, "init" => b });
        assert!(out.contains("compile_error"));
        assert!(out.contains("duplicate entrypoint name"));
    }

    #[test]
    fn rejects_empty_name() {
        let out = expand_str(quote! { "" => init });
        assert!(out.contains("compile_error"));
        assert!(out.contains("must not be empty"));
    }

    #[test]
    fn rejects_malformed_input() {
        let out = expand_str(quote! { init => "init" });
        assert!(out.contains("compile_error"));
    }
}
